# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68092d39bca83e9d1f2606080afa5c32f78905cbdfe39a81a0df4cce04a0722391f9b1c4e4ce8db6343b997d732df884d5f410982bb37896870cbfe7294bf29d

test:
  secret_key_base: e4f9eda9f23a32b33fa0777de68b054e5ab9dcd6bf03fe3c756c3fdf3ba080c218c6c05478db926c3f52e0902b1cec787db44440456b5f1fb2eb24bffd3ae149

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
